[build]
command = "npm run build"
publish = "dist"

# Simple fallback for SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
# Ensure we're using Node.js 18 or higher (required for modern JavaScript features)
NODE_VERSION = "18"

[dev]
framework = "astro"
targetPort = 4321
